name: Daily Job Post

on:
  schedule:
    # Runs at 16:00 UTC (which is 9:00 AM PDT)
    # - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # --- THIS IS THE FIX ---
    # Add this block to grant write permissions to the job's token
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: python3 main.py

      - name: Commit and push posted jobs log
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add posted_jobs.txt
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No new jobs posted, nothing to commit."
          else
            git commit -m "Chore: Update posted jobs log"
            git push
          fi

